### ISSUE TITLE
Considers adding GitLab 

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#13]
We should consider adding GitLab as it is *(imo)* the second most used platform for git hosting 

https://about.gitlab.com/press/press-kit/

**Comment by marzer** [comment]
Yeah this is a good idea; the only reason poxy is aware of just GitHub is just that it's what I use personally, heh.

**Comment by wroyca** [comment]
> Yeah this is a good idea; the only reason poxy is aware of just GitHub is just that it's what I use personally, heh.

I'll try to spare some time this weekend to add GitLab. :)
