### ISSUE TITLE
AttributeError: The Revenge

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#17]
While trying to generate [gnome-builder](https://gitlab.gnome.org/GNOME/gnome-builder) (I know, I know, I only have myself to blame for parsing a C project :sweat: ), I came across this post-processing error: 

```
Post-processing XML files
Traceback (most recent call last):
  File "/home/wroy/.local/lib/python3.11/site-packages/poxy/main.py", line 226, in main
    run(
  File "/home/wroy/.local/lib/python3.11/site-packages/poxy/run.py", line 1619, in run
    postprocess_xml(context)
  File "/home/wroy/.local/lib/python3.11/site-packages/poxy/run.py", line 493, in postprocess_xml
    sections[header.text].append(section)
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

I don't have much information on what's causing this, but let me know if there's some flags you want me to pass for logs and details

**Comment by marzer** [comment]
> I don't have much information on what's causing this

What's causing it is I'm an idiot, lol. I'm checking for null like three lines above this; looks like the action being taken here is just in the wrong scope.

**Comment by marzer** [comment]
Should be fixed now, thanks :)

> but let me know if there's some flags you want me to pass for logs and details

I've added a new `--bug-report` option that will run the whole thing in a subprocess, capture all the output, and zip it up together with all the generated output files. Should streamline the whole process in future, heh.

**Comment by wroyca** [comment]
Amazing, thank!
