### ISSUE TITLE
Please support accesskey="f" for Search

### ISSUE THREAD

**Issue by tim-janik** [marzer/poxy#22]
**Is your feature request related to a problem? Please describe.**

Wikipedia and many other sites support starting up Search on `Shift+Alt+F`.
That'd be nice to have in Poxy output as well.

**Describe the solution you'd like**

I.e. please add code to achieve the equivalent of:

```sh
sed -r '0,/<a class="m-doc-search-icon" href="#search" /s/(<a class="m-doc-search-icon")/\1 accesskey="f"/' -i html/*.html
```

**Additional context**

Other keys are also supported by Wikipedia, e.g. accesskey="z" to go to the Home/front page, but those aren't as frequently used/missed as `Shift+Alt+F` for search.

**Comment by marzer** [comment]
@mosra 

>  Plus, since it has to open a popup, just an accesskey wouldn't be enough I think.

I just tested it via DOM editing and it seems to work OK (on Firefox, at least). It does do something slightly odd with the page layout if you press it _twice_ (i.e. pressing it once again when the search dialog is visible), though it's a pretty minor cosmetic issue.

**Comment by mosra** [comment]
I don't know, if anything I'd just add the key binding next to the other two in the javascript code, I don't see a reason to implement it in a completely different way.

And, again, I think two bindings are enough already, no need to have three. Having this configurable would mean each m.css-based site could have the hotkeys slightly different, which isn't any good for usability. There isn't any consistency across the web with <kbd>Shift</kbd> <kbd>Alt</kbd> <kbd>F</kbd> either, so let's don't mess it up further by also having each m.css search box behave differently.

**Comment by marzer** [comment]
> And, again, I think two bindings are enough already, no need to have three.

Yeh, I'm inclined to agree. I'm just doing a bit of testing for the sake of learning how `accesskey` works. @tim-janik I don't really think this adds any value, personally.

**Comment by marzer** [comment]
@tim-janik I'll add a hook to catch multiple calls to the search function so you can do your own overrides to it without worrying about breaking page state (e.g. using `sed` to apply an `accesskey` in your CI pipeline or wherever). I think that's a good middle ground, since `T` and `TAB` are already sufficient for the vast majority of users.

**Comment by tim-janik** [comment]
Thanks, I'm just used to accesskey="F" from Wikipedia, and indeed I'm using sed atm to add that to the first `<a class="m-doc-search-icon"/>` element. You can test it out here: https://tim-janik.github.io/docs/anklang/

I don't see any page layout issues in Firefox though, and AFAICS a second/third key press does nothing if the search field is already activated.

**Comment by marzer** [comment]
> I don't see any page layout issues in Firefox though, and AFAICS a second/third key press does nothing if the search field is already activated.

On my machine I see the RHS page margin being set to `17px` first time, then `auto` after that. It's not a catastrophic effect by any measure; just looks a bit weird.
