### ISSUE TITLE
Footer misalignement with Mozilla Firefox 110.0 on 3840x2160 (16:9)

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#24]
## Environment

**version and/or commit hash: 0.12.3**

## Describe the bug

The footer may be misaligned in some cases. This is especially apparent with Mozilla Firefox 110.0 on a 3840x2160 (16:9) display scaled at 200%:

![Screenshot from 2023-03-16 08-53-00](https://user-images.githubusercontent.com/91024200/225623574-ffcd4dbe-0ce9-4ce4-9e1f-2e5f9e65e16b.png)

## Bug report

[poxy_bug_report.zip](https://github.com/marzer/poxy/files/10990969/poxy_bug_report.zip)

**Comment by marzer** [comment]
> I suspect the intent was to align with the content of the page disregarding the toc - in which case

Correct; it looked fine before i changed the title-bar to not be constrained to the 'center column' with the rest of the page content, so now it looks a bit odd. It is something I intend to address :)

**Comment by marzer** [comment]
fixed in v0.13.0 :)
