### ISSUE TITLE
Anonymous namespace within another namespace will duplicate top-level namespace

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#28]
## Environment

**version and/or commit hash:**

0.13.4

## Describe the bug

Placing an anonymous namespace within another namespace will duplicate top-level namespace:

a.cxx: 

```cpp
namespace hello
{
  namespace
  {
    void
    say_hello (ostream& o, const string& n)
    {
      if (n.empty ())
        throw invalid_argument ("empty name");
  
      o << "Hello, " << n << '!' << endl;
    }
  }
}
```

b.cxx:
```cpp
namespace hello
{
  namespace
  {
    void
    say_hello (ostream& o, const string& n)
    {
      if (n.empty ())
        throw invalid_argument ("empty name");
  
      o << "Hello, " << n << '!' << endl;
    }
  }
}
```

![image](https://github.com/marzer/poxy/assets/91024200/12d2de23-23a2-41d5-afae-0a2bbe9cb1c0)

## Additional information

It also becomes confused and duplicates elements, such as concept from a.cxx, within both namespaces.

![image](https://github.com/marzer/poxy/assets/91024200/d018ad00-98d3-4439-8fe9-be35b33048f7)

**Comment by marzer** [comment]
Thinking about this, I don't actually this is worth addressing, tbh. Anonymous namespaces are for implementation details in cpp files - running Doxygen over cpp files (i.e. not headers, but actual implementation source files) is unusual. A better fix for this would be simply to not run doxygen/poxy over cpp files at all

**Comment by wroyca** [comment]
> Thinking about this, I don't actually this is worth addressing, tbh. Anonymous namespaces are for implementation details in cpp files - running Doxygen over cpp files (i.e. not headers, but actual implementation source files) is unusual. A better fix for this would be simply to not run doxygen/poxy over cpp files at all

Agree - Note that it was a long time ago, so I don't remember the context, but that may have been from playing with modules here (where the extension name is arbitrary with some build system)

**Comment by wroyca** [comment]
Closing \:)
