### ISSUE TITLE
Multi-row navbar occludes page content

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#3]
The GitHub icon causes Poxy to incorrectly overlaps with long project description, as shown below:

![A](https://user-images.githubusercontent.com/91024200/184725162-dc571d4b-24ca-4e71-9130-fe3180da0e2d.png)

![B](https://user-images.githubusercontent.com/91024200/184725100-86e8436a-4436-49f7-aad4-c05bc9799066.png)

**Comment by marzer** [comment]
O_O

I... I don't even know where to start with this, hah. The github icon shouldn't have any impact on the page flow at all, it's just the `background-image` CSS attribute.

How did you generate the second image, without the issue?

**Comment by wroyca** [comment]
> O_O
> 
> I... I don't even know where to start with this, hah. The github icon shouldn't have any impact on the page flow at all, it's just the `background-image` CSS attribute.
> 
> How did you generate the second image, without the issue?

Disabling margin-top in h1, h2, h3, h4, h5, h6 corrects the problem to some extent *(not perfect*) :

The second image was generated by refreshing before completion, just before the logo is available to be shown

Note: the issue can't be reproduced with m.css


```css
h1, h2, h3, h4, h5, h6 {
  /* margin-top: 0; */
  font-weight: 600;
}
```

![image](https://user-images.githubusercontent.com/91024200/184726558-75607879-9a20-4a31-990a-7efc0b87da3b.png)

m.css (left):

![Screenshot 2022-08-15 175053](https://user-images.githubusercontent.com/91024200/184726754-0b4ab679-a8de-4ec1-b105-c43ac5ee68a7.png)

**Comment by marzer** [comment]
> Note: the issue can't be reproduced with m.css

Yeah; I modified the page header to stay fixed in place at the top of the window, whereas m.css leaves it just as a regular, non-floating page element. For this to work I had to increase the top margin of the page content by the regular height of the navbar so that when you're viewing the top of the window it looks 'vanilla'. I suspect the root of the issue here is actually that you're seeing a two-row header, and my CSS adjustments don't take that possibility into account.

**Comment by marzer** [comment]
I won't have time to engineer a decent fix for this until at least this weekend, but you can add an override to some custom CSS of your own to restore the m.css behaviour:

```css
body
{
	padding-top: initial !important;
}

body > header
{
	position: initial !important;
}
```

**Comment by marzer** [comment]
using the changes above:

![image](https://user-images.githubusercontent.com/3958019/184727848-552dc1e7-47c5-4235-b784-5b5b90e12ac5.png)

**Comment by wroyca** [comment]
> I won't have time to engineer a decent fix for this until at least this weekend, but you can add an override to some custom CSS of your own to restore the m.css behaviour:
> 
> ```css
> body
> {
> 	padding-top: initial !important;
> }
> 
> body > header
> {
> 	position: initial !important;
> }
> ```

It's ok, there's no rush, thanks for the alternative 👍
