### ISSUE TITLE
Automatically document directories by creating respective dox files

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#30]
## Is your feature request related to a problem? Please describe.

Referring to https://github.com/marzer/poxy/issues/21#issuecomment-1449182509, "registering" documented files with Doxygen stands out as notably user-hostile, particularly when dealing with local installations. In short, with a local project structure, we must "describe" each directory from our source-tree, as these directories don't rely on relative paths. For example: 

```cpp
/// @dir C:/Users/wroy/Desktop
/// @brief a

/// @dir echo
/// @brief b

/// @dir echo/echo
/// @brief c

/// @file echo.hxx
/// @brief d
```

This doesn't transition effectively to CI or to another individual's computer. In such cases, they would need to modify "C:/Users/wroy/Desktop" to indicate the correct absolute path.

## Describe the solution you'd like

During the generation phase, it might be advisable to automatically document directories (using path or recursive_path as context) by creating respective dox files with "@dir" and "@brief" annotations. If a user wishes to furnish directory description, then a manually created dox file should take precedence

## Additional context

☕

**Comment by marzer** [comment]
oooooh that's a great idea, and likely quite easy to implement

**Comment by mosra** [comment]
> This doesn't transition effectively to CI or to another individual's computer.

This seems to be a recurring issue that everyone suffers from which I myself never had a problem with. I've never needed to include _the full path_ for the `@dir` or `@file` commands, never in the 15 years of working with Doxygen. There were insane bugs all over, but this was never a problem. So I'd like to understand what is it everyone else is doing differently that they run into this :D What are your `INPUT`, `STRIP_FROM_PATH` and `STRIP_FROM_INC_PATH` settings? 

See also [this comment](https://github.com/mosra/m.css/issues/137#issuecomment-723479673).

**Comment by mosra** [comment]
And I assume you want `/home/wroy/hello` stripped away, right?

The relevant Doxyfile parts are this:

```ini
STRIP_FROM_PATH        = "/tmp/poxy/bug_report/temp/pages"
STRIP_FROM_INC_PATH    =
INPUT                  = "/home/wroy/hello/hello" \
                         "/home/wroy/hello/libhello" \
                         "/tmp/poxy/bug_report/temp/pages"
```

Not sure what's the temp pages directory but it should be something like this instead, I think, then it wouldn't include the whole path in the file list. The project root is probably something the project configuration itself should specify, can't really automate that I think -- there's not really a way to know whether it's meant to be `#include <libhello/hello.h>` or just `#include <hello.h>`.

```ini
STRIP_FROM_PATH        = "/home/wroy/hello" \
                         "/tmp/poxy/bug_report/temp/pages"
STRIP_FROM_INC_PATH    = "/home/wroy/hello"
INPUT                  = "/home/wroy/hello/hello" \
                         "/home/wroy/hello/libhello" \
                         "/tmp/poxy/bug_report/temp/pages"
```

**Comment by mosra** [comment]
Alright, thanks for clarifying :)

> which is what becomes doxygen's `STRIP_FROM_PATH`.

So I assume it does basically what I suggested above, right? I wonder if this is where poxy automagic would help, i.e. setting the `STRIP_FROM_*_PATH` implicitly to _something_. Which might be possibly wrong (stripping too much), but in my opinion better than having `C:/` or `/home/whoever` shown in the output :D

**Comment by marzer** [comment]
@wroyca I promise you you don't need to be explicit about paths at any point, _apart_ from the 'strip from' setting. You are doing something weird that isn't obvious to me.

**Comment by marzer** [comment]
Well yes, but that's by design? You don't need to be explicit in your `@dir` annotations, so I dont understand what the issue is.

**Comment by marzer** [comment]
Like, you pretty much _have_ to use `strip_paths` / `STRIP_FROM_PATH`. I should make it emit a warning in poxy when it's omitted, tbh.

Unless we want to get into guessing the project root, but that's orthogonal to the idea of autogenerating `@dir` entries.

**Comment by mosra** [comment]
Yeah, that's the problem, you're using absolute paths. Don't use them. Anywhere. If everything is relative to the Doxyfile, the `INPUT`, the `STRIP_FROM_PATH`, etc., then it works.
