### ISSUE TITLE
Namespace ignoring (detail)

### ISSUE THREAD

**Issue by Guekka** [marzer/poxy#36]
**Is your feature request related to a problem? Please describe.**

I would like to ignore everything in the `detail` namespace.

**Describe the solution you'd like**

Doxygen has [EXCLUDE_SYMBOLS](https://www.doxygen.nl/manual/config.html#cfg_exclude_symbols)
Simply exposing it in the config should be enough

**Comment by marzer** [comment]
Ah! This is a great idea. I did not even realise doxygen had this feature - I would have use for it myself 😅 Thanks for the suggestion.

**Comment by marzer** [comment]
This feature is now available in v0.18.0 :)
