### ISSUE TITLE
GitHub CIs no longer work with v0.7.0 

### ISSUE THREAD

**Issue by wroyca** [marzer/poxy#9]
GitHub CIs are still using Python 3.8, which results in incompatibility with v0.7.0. It seems to have been missed by Poxy CI since it never ran Poxy itself - the tests are never used. 

```bash
Traceback (most recent call last):
  File "/usr/local/bin/poxy", line 5, in <module>
    from poxy.main import main
  File "/usr/local/lib/python3.8/dist-packages/poxy/main.py", line 1[7](https://github.com/wroyca/rune/runs/8239827362?check_suite_focus=true#step:4:8), in <module>
    from . import css
  File "/usr/local/lib/python3.[8](https://github.com/wroyca/rune/runs/8239827362?check_suite_focus=true#step:4:9)/dist-packages/poxy/css.py", line 28, in <module>
    def resolve_imports(text, cwd=None, mcss_dir = None) -> tuple[str, bool]:
TypeError: 'type' object is not subscriptable
```

**Comment by wroyca** [comment]
For ref: https://stackoverflow.com/a/66154081

**Comment by marzer** [comment]
What? I used it with toml++'s CI already. Worked fine.

**Comment by marzer** [comment]
My config: https://github.com/marzer/tomlplusplus/blob/master/.github/workflows/gh-pages.yaml

**Comment by marzer** [comment]
Oh, just saw your link. Well if that's all it is I can easily patch that, heh.

**Comment by wroyca** [comment]
Odd. Two different projects of mine worked fine prior to this version and CI suddently stopped for both. I'll have a look at your config tomorrow. For mine you can look at:
 https://github.com/wroyca/rune/.github/workflows/gh-pages.yml

Which is a very simple ubuntu-latest CI 

*Sorry if the link is slightly wrong, I'm using my phone.*

**Comment by marzer** [comment]
Yeah I think the discriminator here is that in my toml++ CI i'm explicitly invoking `apt get install python3` so it's probably updating it post-3.8. I'll push a poxy update to fix that type annotation so that isn't necessary.

> Poxy CI since it never ran Poxy itself - the tests are never used.

Heh, yeah. There's no tests currently; I set up some CI to blast out different versions of Doxygen and _started_ writing a framework for diffing poxy outputs, but ran out of steam. Definitely need to square that circle at some point.

**Comment by marzer** [comment]
Ah, it's likely because I'm doing this:

```yaml
    container:
      image: debian:testing
```

That was necessary for something in toml++'s CI (linux shenanigans, I dunno), and I suppose 've unthinkingly copied it into the GH pages workflow 😅

**Comment by wroyca** [comment]
> ~Yeah I think the discriminator here is that in my toml++ CI i'm explicitly invoking `apt get install python3` so it's probably updating it post-3.8. I'll push a poxy update to fix that type annotation so that isn't necessary.~ Oh, so are you. I have no idea then.
> 
> > Poxy CI since it never ran Poxy itself - the tests are never used.
> 
> Heh, yeah. There's no tests currently; I set up some CI to blast out different versions of Doxygen and _started_ writing a framework for diffing poxy outputs, but ran out of steam. Definitely need to square that circle at some point.

Had a quick look, you re-synchronize the package index files from their sources and then install python which now fetch most likely 3.9~3.10. Mine doesn't re-synchronize and instead use it as it is with the image by default, therefore pulling 3.8. I can fix that on my end :)

**Comment by marzer** [comment]
Also @wroyca in 0.7.0 I made a start on the light theme, as well as doing some minor style tweaks to the navbar. Looking forward to hearing what you think. Also will happily accept any contributions ot the light theme as it is still somewhat experimental (the idea being that when it's 'finished' I'll contribute it back to m.css itself).

**Comment by wroyca** [comment]
> Also @wroyca in 0.7.0 I made a start on the light theme, as well as doing some minor style tweaks to the navbar. Looking forward to hearing what you think.
> 
> Will happily accept any contributions ot the light theme as it is still somewhat experimental (the idea being that when it's 'finished' I'll contribute it back to m.css itself).

@marzer I'm really impressed with the tenfold improvements that have been made in the last few days. The light theme is great! A few nitpicks here and there on the contrast but overall it's beautiful. 😇 

I'd also like to help with feedback and PR, do you have a Poxy related discord / slack / irc / gitter that we can discuss on? This would be more appropriate for discussing color contrast than, say, a issue board

**Comment by marzer** [comment]
High praise! Glad you like it :)

Just made a gitter: https://gitter.im/marzer/poxy
